version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing Angular CLI and dependencies...
      - npm cache clean --force
      - npm install -g @angular/cli
      - npm ci || npm install
  build:
    commands:
      - echo Build started on `date`
      - ng build --configuration production
artifacts:
  files:
    - '**/*'
  base-directory: dist/angular-food-frontend



