version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install -g @angular/cli
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - ng build --configuration production

artifacts:
  files:
    - '**/*'
  base-directory: dist/angular-food-frontend


